name: Greeting on variable day

on:
  workflow_dispatch:
   inputs:
    username:
     description: "eneter your name"
     required: true
     default: "guset"


jobs:
  get-usename:
    runs-on: ubuntu-latest
    outputs: 
      name: ${{steps.get-name.outputs.name}}
    steps:
      - id: get-name
      - name: "print variable"
        run: echo "user is:${{github.event.inputs.username}}" >> $GITHUB_OUTPUT

  get-output:
      runs-on: ubuntu-latest
      steps:
       - run: echo "name from previous job is ${{needs.get-username.outputs.username}}"
